steps:

  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/assign2-450821/mihir-100947380/frontend-app:$COMMIT_SHA"
      - "."

  #Push Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/assign2-450821/mihir-100947380/frontend-app:$COMMIT_SHA"

  #Deploy to Cloud Run (For Continuous Deployment)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "frontend-app"
      - "--image"
      - "us-central1-docker.pkg.dev/assign2-450821/mihir-100947380/frontend-app:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "3000"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: "us-central1"

images:
  - "us-central1-docker.pkg.dev/assign2-450821/mihir-100947380/frontend-app:$COMMIT_SHA"
