steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/assign2-450821/mihir-100947380/frontend-app:$COMMIT_SHA"
      - "."

  # Step 2: Push Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/assign2-450821/mihir-100947380/frontend-app:$COMMIT_SHA"


options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: "us-central1"

images:
  - "us-central1-docker.pkg.dev/assign2-450821/mihir-100947380/frontend-app:$COMMIT_SHA"
